name: "Bug"
description: "Report a Bug"
title: "[Bug]"
labels: "bug"
assignees: ""
issue_body: false
body:
  - type: markdown
    attributes:
      value: |
        ### Use this form to report a Bug in a Tachiyomi extension.
  - type: input
    attributes:
      label: Tachiyomi Version
      description: "Tachiyomi Version"
      placeholder: "0.10.12"
    validations:
      required: true
  - type: input
      attributes:
        label: Android Version
        description: "Android Version"
        placeholder: "8.1.0"
      validations:
        required: true
  - type: input
      attributes:
        label: Extension Name
        description: "Extension Name"
        placeholder: "Mangadex"
      validations:
        required: true
  - type: input
      attributes:
        label: Extension Version
        description: "Extension Version"
        placeholder: "1.2.1"
      validations:
        required: true
  - type: textarea
      attributes:
        label: Steps to reproduce
        description: "Steps to reproduce"
        placeholder: "1. Search 'Dragon Ball' in Mangadex"
      validations:
        required: true
  - type: textarea
      attributes:
        label: Expected behavior
        description: "Expected behavior"
        placeholder: "Display the Dragon Ball manga"
      validations:
        required: true
  - type: textarea
      attributes:
        label: Actual behavior
        description: "Actual behavior"
        placeholder: "No Manga is shown"
      validations:
        required: true
  - type: textarea
      attributes:
        label: Other details
        description: "Other details"
        placeholder: "If i try searching just Dragon it find it"
      validations:
        required: false

